// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"

TEST_CASE("Ex1 makeHashMap() ", "[example]")
{
	string filename;
	map<string, vector<string>> hashMap;

	filename = "test0.txt";
	makeHashMap(filename, hashMap);
	printMap(hashMap);

	map<string, vector<string>>::iterator it;
	it = hashMap.begin();
	REQUIRE(hashMap["is"][0] == "hot");
	REQUIRE(hashMap["like"][0] == "apple");
}

TEST_CASE("Ex2 makeHashMap() ", "[example]")
{
	string filename;
	map<string, vector<string>> hashMap;

	filename = "Markov.txt";
	makeHashMap(filename, hashMap);
	printMap(hashMap);

	map<string, vector<string>>::iterator it;
	it = hashMap.begin();
	REQUIRE(hashMap["to"][0] == "generate");
	REQUIRE(hashMap["on"][0] == "the");
	REQUIRE(hashMap["sentences"][0] == "based");
}